### ISSUE TITLE
3x slower than GNU parallel on "cat" command and parameters on stdin

### ISSUE THREAD

**Issue by Shnatsel** [mmstick/parallel#21]
I've tested Rust parallel on 10,000 files and it's now significantly slower on a simple 'cat' workload than gnu parallel. The command line is:

`find '/folder/with/lots/of/text/files/' -type f | head -n 10000 | parallel -j 6 cat '{}' > /dev/null`

Runtime and peak memory usage for each:
rust: 1:40, 36,8MiB
rust, --no-shell: 1:36, 58,9MiB
gnu: 0:31, 14,6MiB

Additionally, the memory usage for Rust parallel grows over time while GNU parallel uses a fixed amount of memory.

For the record, the regular use case for this is piping all that stuff to grep instead of /dev/null to get aggregate statistics for the entire dataset.

**Comment by mmstick** [comment]
Interesting that memory consumption increases with `--no-shell`, when `-no-shell` is doing less by not executing commands inside `sh`. GNU Parallel gets away with using less memory because it dumps the standard output and error of each process to a temporary location on the disk, so I can achieve similar reduction by buffering to the disk as I am doing with input arguments.

As for slowness, I'm not sure what would be causing your performance issues. On my systems, this Rust implementation is always faster by at least a magnitude or more.

**Comment by Shnatsel** [comment]
Duplicate of #22
